### ISSUE TITLE
Send /messages response in a JSON object ?

### ISSUE THREAD

**Issue by ElliotThiebaut** [ElliotThiebaut/ettt-api#13]
Currently, the API sends back an Array of message, maybe for consistency the API should send back a JSON object with all the messages instead of an array.

**Comment by killian-mahe** [comment]
Do you have a schema of your response ?

**Comment by ElliotThiebaut** [comment]
The response schema is available in the [documentation](https://ettt-cloud.stoplight.io/docs/ettt-cloud-api).

A feature branch has been created if you want to implement the feature !

**Comment by ElliotThiebaut** [comment]
The real question is : Should an array of messages be send back as JSON for the sack of consistency or should we leave it as an array to make it easier for people using the API to use the information send back ?

Is it against a convention to respond with an array ? It seems way easier to deal with for the frontend but the API declares a response in JSON so it's not a awaited response type... 🤔

**Comment by killian-mahe** [comment]
Well, the top level of a JSON response can be either an "array" or an object. In either case, it is a valid JSON object.
There are multiple standards for defining JSON, but all agree that you can use either solution.

The question is, which solution is better for the evolution of the API?
And I think the best solution is to use an object. Because in your future developments, you might need to add metadata to your API response, like the total number of messages or any other piece of information : 

```json
{
  "username": "my-username",
  "messages": [
    {
      "id": 5,
      "content": "Hello world !"
    },
    ...
  ]
}
```
